on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.16.1
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11.0.2
          distribution: 'jdk
